apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s]

    processors:
      batch:

    exporters:
      debug:
        verbosity: basic
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9464"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger, spanmetrics, debug]
        metrics:
          receivers: [spanmetrics]
          processors: [batch]
          exporters: [prometheus, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
  labels:
    app: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetrycollector
  template:
    metadata:
      labels:
        app: opentelemetrycollector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.96.0
        args:
        - --config=/conf/config.yaml
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 9464
          name: prom-metrics
        - containerPort: 8888
          name: self-metrics
        volumeMounts:
        - name: config
          mountPath: /conf
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
  labels:
    app: opentelemetrycollector
spec:
  selector:
    app: opentelemetrycollector
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
  - name: http-otlp
    port: 4318
    targetPort: 4318
  - name: prom-metrics
    port: 9464
    targetPort: 9464
  - name: self-metrics
    port: 8888
    targetPort: 8888
